#pragma once

/**********************
 * ANIMATION SETTINGS *
 **********************/

enum {
    ANIM_AVAILABILITY_DONT_USE,
    ANIM_AVAILABILITY_ONLY_ROOT,
    ANIM_AVAILABILITY_ALL_BONES,
    ANIM_AVAILABILITY_IDENTIFIER
}

enum {
    ANIM_VALUE_TYPE_INTEGER,
    ANIM_VALUE_TYPE_BFLOAT,
    ANIM_VALUE_TYPE_SHORT_BFLOAT,
    ANIM_VALUE_TYPE_FIXED_BFLOAT, // Fixed exponent bfloat
}

enum {
    ANIM_PER_ELEMENT_INDICE,
    ANIM_PER_TRANSFORM_INDICE,
}
enum {
    ANIM_STRUCTURE_INDEX,
    ANIM_STRUCTURE_CONTINUOUS,
}

// #define USE_TRANSLATION_FLAGS
// #define USE_Y_DIVISOR

#define ANIM_INDEX_TYPE ANIM_PER_ELEMENT_INDICE
#define ANIM_DATA_STRUCTURE ANIM_STRUCTURE_INDEX


// Translation Settings
#define ANIM_TRANS_AVAILABILITY     ANIM_AVAILABILITY_ONLY_ROOT
#if ANIM_TRANS_AVAILABILITY != ANIM_AVAILABILITY_DONT_USE
    #if ANIM_TRANS_AVAILABILITY != ANIM_AVAILABILITY_IDENTIFIER
        #define ANIM_TRANS_IDENTIFIER       65536
    #endif
    #define ANIM_TRANS_VALUE_TYPE       ANIM_VALUE_TYPE_INTEGER
#endif

// Scale Settings
#define ANIM_SCALE_AVAILABILITY     ANIM_AVAILABILITY_DONT_USE
#if ANIM_SCALE_AVAILABILITY != ANIM_AVAILABILITY_DONT_USE
    #if ANIM_ROTATION_AVAILABILITY != ANIM_AVAILABILITY_IDENTIFIER
        #define ANIM_SCALE_IDENTIFIER       65535
    #endif
    #define ANIM_SCALE_VALUE_TYPE       ANIM_VALUE_TYPE_BFLOAT
#endif

// Rotation Settings
#define ANIM_ROTATION_AVAILABILITY  ANIM_AVAILABILITY_ALL_BONES
#if ANIM_ROTATION_AVAILABILITY != ANIM_AVAILABILITY_DONT_USE
    #if ANIM_ROTATION_AVAILABILITY != ANIM_AVAILABILITY_IDENTIFIER
        #define ANIM_ROTATION_IDENTIFIER    65534
    #endif
    #define ANIM_ROTATION_VALUE_TYPE    ANIM_VALUE_TYPE_BFLOAT
    #define ANIM_THREE_ELEMENT_QUATERNION
#endif