#include "src/game/envfx_snow.h"

const GeoLayout bob_area_2_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SCENE_LIGHT(LIGHT_TYPE_AMBIENT, 78, 97, 126, 0, 0, 0),
		GEO_TRANSLATE_NODE(LAYER_OPAQUE, 0, -2935, 0),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bob_dl_Geo_area_2_mesh_layer_1),
		GEO_TRANSLATE_NODE_WITH_DL(LAYER_TRANSPARENT, -178, -301, -2038, bob_dl_Geo_area_2_001_mesh_layer_5),
		GEO_ASM(0, geo_shyguy_mask_render),
		GEO_TRANSLATE_NODE(LAYER_OPAQUE, 0, -2935, 0),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_OPAQUE, bob_dl_Hidden_geo_area_2_mesh_layer_1),
			GEO_DISPLAY_LIST(LAYER_TRANSPARENT_DECAL, bob_dl_Hidden_geo_area_2_mesh_layer_6),
		GEO_CLOSE_NODE(),
		GEO_SCENE_LIGHT(LIGHT_TYPE_DIRECTIONAL, 95, 183, 139, 0, 90, 0),
		GEO_TRANSLATE_NODE(LAYER_OPAQUE, 0, -2935, 0),
		GEO_TRANSLATE_NODE(LAYER_OPAQUE, 1664, 240, -2538),
		GEO_OPEN_NODE(),
			GEO_ASM(2, geo_pillar_puzzle),
			GEO_DISPLAY_LIST(LAYER_OPAQUE, bob_dl_Pillar_mesh_layer_1),
		GEO_CLOSE_NODE(),
		GEO_ASM(1, geo_shyguy_mask_render),
		GEO_TRANSLATE_NODE(LAYER_OPAQUE, 0, -2935, 0),
		GEO_OPEN_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout bob_area_2[] = {
	GEO_NODE_SCREEN_AREA(10, SCREEN_WIDTH/2, SCREEN_HEIGHT/2, SCREEN_WIDTH/2, SCREEN_HEIGHT/2),
	GEO_OPEN_NODE(),
		GEO_ZBUFFER(0),
		GEO_OPEN_NODE(),
			GEO_NODE_ORTHO(100.0000),
			GEO_OPEN_NODE(),
				GEO_BACKGROUND_COLOR(0x0001),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_ZBUFFER(1),
		GEO_OPEN_NODE(),
			GEO_CAMERA_FRUSTUM_WITH_FUNC(45.0000, 100, 30000, geo_camera_fov),
			GEO_OPEN_NODE(),
				GEO_CAMERA(CAMERA_MODE_8_DIRECTIONS, 0, 2935, 0, 0, 2835, 0, geo_camera_main),
				GEO_OPEN_NODE(),
					GEO_BRANCH(1, bob_area_2_geo),
					GEO_RENDER_OBJ(),
					GEO_ASM(ENVFX_MODE_NONE, geo_envfx_main),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bob_dl_material_revert_render_settings),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, bob_dl_material_revert_render_settings),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT_DECAL, bob_dl_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
