#include "src/game/envfx_snow.h"

const GeoLayout peach_1_transparency_from_anim_state_opt1_eye_switch_opt1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SWITCH_CASE(2, geo_switch_peach_lips),
		GEO_OPEN_NODE(),
			GEO_NODE_START(),
			GEO_OPEN_NODE(),
				GEO_ANIMATED_PART(LAYER_TRANSPARENT, 132, 0, 0, peach_head_mesh_layer_1_mat_override_eye_mostly_open_0),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout peach_1_transparency_from_anim_state_opt1_eye_switch_opt2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SWITCH_CASE(2, geo_switch_peach_lips),
		GEO_OPEN_NODE(),
			GEO_NODE_START(),
			GEO_OPEN_NODE(),
				GEO_ANIMATED_PART(LAYER_TRANSPARENT, 132, 0, 0, peach_head_mesh_layer_1_mat_override_eye_mostly_closed_1),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout peach_1_transparency_from_anim_state_opt1_eye_switch_opt3[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SWITCH_CASE(2, geo_switch_peach_lips),
		GEO_OPEN_NODE(),
			GEO_NODE_START(),
			GEO_OPEN_NODE(),
				GEO_ANIMATED_PART(LAYER_TRANSPARENT, 132, 0, 0, peach_head_mesh_layer_1_mat_override_eye_closed_2),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout peach_1_transparency_from_anim_state_opt1_eye_switch_opt0_lips_switch_opt1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT, 132, 0, 0, peach_head_mesh_layer_1_mat_override_lips_scrunched_3),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout peach_1_transparency_from_anim_state_opt1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, peach_root_mesh_layer_1),
		GEO_OPEN_NODE(),
			GEO_ANIMATED_PART(LAYER_TRANSPARENT, -23, -1, 0, peach_dress_mesh_layer_1),
			GEO_ANIMATED_PART(LAYER_TRANSPARENT, 78, 0, 0, peach_neck_mesh_layer_1),
			GEO_ANIMATED_PART(LAYER_TRANSPARENT, 78, 0, 0, peach_torso_mesh_layer_1),
			GEO_OPEN_NODE(),
				GEO_SWITCH_CASE(4, geo_switch_peach_eyes),
				GEO_OPEN_NODE(),
					GEO_NODE_START(),
					GEO_OPEN_NODE(),
						GEO_SWITCH_CASE(2, geo_switch_peach_lips),
						GEO_OPEN_NODE(),
							GEO_NODE_START(),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_TRANSPARENT, 132, 0, 0, peach_head_mesh_layer_1),
							GEO_CLOSE_NODE(),
							GEO_BRANCH(1, peach_1_transparency_from_anim_state_opt1_eye_switch_opt0_lips_switch_opt1),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
					GEO_BRANCH(1, peach_1_transparency_from_anim_state_opt1_eye_switch_opt1),
					GEO_BRANCH(1, peach_1_transparency_from_anim_state_opt1_eye_switch_opt2),
					GEO_BRANCH(1, peach_1_transparency_from_anim_state_opt1_eye_switch_opt3),
				GEO_CLOSE_NODE(),
				GEO_ANIMATED_PART(LAYER_TRANSPARENT, 63, 0, 84, peach_left_arm_mesh_layer_1),
				GEO_ANIMATED_PART(LAYER_TRANSPARENT, 63, 0, 84, peach_left_shoulder_mesh_layer_1),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_TRANSPARENT, 104, 0, 0, peach_left_elbow_mesh_layer_1),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_TRANSPARENT, 87, 0, 0, peach_left_hand_mesh_layer_1),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
				GEO_ANIMATED_PART(LAYER_TRANSPARENT, 170, -78, 0, peach_lower_hair_mesh_layer_1),
				GEO_ANIMATED_PART(LAYER_TRANSPARENT, 63, 0, -84, peach_right_arm_mesh_layer_1),
				GEO_ANIMATED_PART(LAYER_TRANSPARENT, 63, 0, -84, peach_right_shoulder_mesh_layer_1),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_TRANSPARENT, 104, 0, 0, peach_right_elbow_mesh_layer_1),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_TRANSPARENT, 87, 0, 0, peach_right_hand_mesh_layer_1),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout peach_1_transparency_from_anim_state_opt0_eye_switch_opt1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SWITCH_CASE(2, geo_switch_peach_lips),
		GEO_OPEN_NODE(),
			GEO_NODE_START(),
			GEO_OPEN_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 132, 0, 0, peach_head_mesh_layer_1_mat_override_eye_mostly_open_0),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout peach_1_transparency_from_anim_state_opt0_eye_switch_opt2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SWITCH_CASE(2, geo_switch_peach_lips),
		GEO_OPEN_NODE(),
			GEO_NODE_START(),
			GEO_OPEN_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 132, 0, 0, peach_head_mesh_layer_1_mat_override_eye_mostly_closed_1),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout peach_1_transparency_from_anim_state_opt0_eye_switch_opt3[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SWITCH_CASE(2, geo_switch_peach_lips),
		GEO_OPEN_NODE(),
			GEO_NODE_START(),
			GEO_OPEN_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 132, 0, 0, peach_head_mesh_layer_1_mat_override_eye_closed_2),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout peach_1_transparency_from_anim_state_opt0_eye_switch_opt0_lips_switch_opt1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 132, 0, 0, peach_head_mesh_layer_1_mat_override_lips_scrunched_3),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout peach_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SHADOW(0, 150, 100),
		GEO_OPEN_NODE(),
			GEO_SCALE(LAYER_OPAQUE, 16384),
			GEO_OPEN_NODE(),
				GEO_ASM(10, geo_update_layer_transparency),
				GEO_SWITCH_CASE(2, geo_switch_anim_state),
				GEO_OPEN_NODE(),
					GEO_NODE_START(),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, peach_root_mesh_layer_1),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, -23, -1, 0, peach_dress_mesh_layer_1),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 78, 0, 0, peach_neck_mesh_layer_1),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 78, 0, 0, peach_torso_mesh_layer_1),
							GEO_OPEN_NODE(),
								GEO_SWITCH_CASE(4, geo_switch_peach_eyes),
								GEO_OPEN_NODE(),
									GEO_NODE_START(),
									GEO_OPEN_NODE(),
										GEO_SWITCH_CASE(2, geo_switch_peach_lips),
										GEO_OPEN_NODE(),
											GEO_NODE_START(),
											GEO_OPEN_NODE(),
												GEO_ANIMATED_PART(LAYER_OPAQUE, 132, 0, 0, peach_head_mesh_layer_1),
											GEO_CLOSE_NODE(),
											GEO_BRANCH(1, peach_1_transparency_from_anim_state_opt0_eye_switch_opt0_lips_switch_opt1),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
									GEO_BRANCH(1, peach_1_transparency_from_anim_state_opt0_eye_switch_opt1),
									GEO_BRANCH(1, peach_1_transparency_from_anim_state_opt0_eye_switch_opt2),
									GEO_BRANCH(1, peach_1_transparency_from_anim_state_opt0_eye_switch_opt3),
								GEO_CLOSE_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 63, 0, 84, peach_left_arm_mesh_layer_1),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 63, 0, 84, peach_left_shoulder_mesh_layer_1),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(LAYER_OPAQUE, 104, 0, 0, peach_left_elbow_mesh_layer_1),
									GEO_OPEN_NODE(),
										GEO_ANIMATED_PART(LAYER_OPAQUE, 87, 0, 0, peach_left_hand_mesh_layer_1),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 170, -78, 0, peach_lower_hair_mesh_layer_1),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 63, 0, -84, peach_right_arm_mesh_layer_1),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 63, 0, -84, peach_right_shoulder_mesh_layer_1),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(LAYER_OPAQUE, 104, 0, 0, peach_right_elbow_mesh_layer_1),
									GEO_OPEN_NODE(),
										GEO_ANIMATED_PART(LAYER_OPAQUE, 87, 0, 0, peach_right_hand_mesh_layer_1),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
					GEO_BRANCH(1, peach_1_transparency_from_anim_state_opt1),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
