extern const GeoLayout peach_1_transparency_from_anim_state_opt1_eye_switch_opt1[];
extern const GeoLayout peach_1_transparency_from_anim_state_opt1_eye_switch_opt2[];
extern const GeoLayout peach_1_transparency_from_anim_state_opt1_eye_switch_opt3[];
extern const GeoLayout peach_1_transparency_from_anim_state_opt1_eye_switch_opt0_lips_switch_opt1[];
extern const GeoLayout peach_1_transparency_from_anim_state_opt1[];
extern const GeoLayout peach_1_transparency_from_anim_state_opt0_eye_switch_opt1[];
extern const GeoLayout peach_1_transparency_from_anim_state_opt0_eye_switch_opt2[];
extern const GeoLayout peach_1_transparency_from_anim_state_opt0_eye_switch_opt3[];
extern const GeoLayout peach_1_transparency_from_anim_state_opt0_eye_switch_opt0_lips_switch_opt1[];
extern const GeoLayout peach_geo[];
extern u8 peach_peach_dress_rgba16_rgba16[];
extern u8 peach_peach_eye_open_rgba16_rgba16[];
extern u8 peach_peach_lips_rgba16_rgba16[];
extern u8 peach_peach_nostril_rgba16_rgba16[];
extern u8 peach_peach_crown_jewel_rgba16_rgba16[];
extern u8 peach_peach_eye_mostly_open_rgba16_rgba16[];
extern u8 peach_peach_eye_mostly_closed_rgba16_rgba16[];
extern u8 peach_peach_eye_closed_rgba16_rgba16[];
extern u8 peach_peach_lips_scrunched_rgba16_rgba16[];
extern Vtx peach_root_mesh_layer_1_vtx_0[48];
extern Vtx peach_dress_mesh_layer_1_vtx_0[64];
extern Vtx peach_neck_mesh_layer_1_vtx_0[10];
extern Vtx peach_torso_mesh_layer_1_vtx_0[57];
extern Vtx peach_torso_mesh_layer_1_vtx_1[5];
extern Vtx peach_head_mesh_layer_1_vtx_0[41];
extern Vtx peach_head_mesh_layer_1_vtx_1[89];
extern Vtx peach_head_mesh_layer_1_vtx_2[5];
extern Vtx peach_head_mesh_layer_1_vtx_3[3];
extern Vtx peach_head_mesh_layer_1_vtx_4[36];
extern Vtx peach_head_mesh_layer_1_vtx_5[32];
extern Vtx peach_left_arm_mesh_layer_1_vtx_0[13];
extern Vtx peach_left_arm_mesh_layer_1_vtx_1[12];
extern Vtx peach_left_shoulder_mesh_layer_1_vtx_0[21];
extern Vtx peach_left_elbow_mesh_layer_1_vtx_0[14];
extern Vtx peach_left_hand_mesh_layer_1_vtx_0[23];
extern Vtx peach_lower_hair_mesh_layer_1_vtx_0[54];
extern Vtx peach_right_arm_mesh_layer_1_vtx_0[13];
extern Vtx peach_right_arm_mesh_layer_1_vtx_1[12];
extern Vtx peach_right_shoulder_mesh_layer_1_vtx_0[21];
extern Vtx peach_right_elbow_mesh_layer_1_vtx_0[14];
extern Vtx peach_right_hand_mesh_layer_1_vtx_0[23];
extern Gfx peach_root_mesh_layer_1[];
extern Gfx peach_dress_mesh_layer_1[];
extern Gfx peach_neck_mesh_layer_1[];
extern Gfx peach_torso_mesh_layer_1[];
extern Gfx peach_head_mesh_layer_1[];
extern Gfx peach_head_mesh_layer_1_mat_override_eye_mostly_open_0[];
extern Gfx peach_head_mesh_layer_1_mat_override_eye_mostly_closed_1[];
extern Gfx peach_head_mesh_layer_1_mat_override_eye_closed_2[];
extern Gfx peach_head_mesh_layer_1_mat_override_lips_scrunched_3[];
extern Gfx peach_left_arm_mesh_layer_1[];
extern Gfx peach_left_shoulder_mesh_layer_1[];
extern Gfx peach_left_elbow_mesh_layer_1[];
extern Gfx peach_left_hand_mesh_layer_1[];
extern Gfx peach_lower_hair_mesh_layer_1[];
extern Gfx peach_right_arm_mesh_layer_1[];
extern Gfx peach_right_shoulder_mesh_layer_1[];
extern Gfx peach_right_elbow_mesh_layer_1[];
extern Gfx peach_right_hand_mesh_layer_1[];
