#include "anim_0 - Listen Everybody.inc.c"
#include "anim_1 - Turning Away.inc.c"
#include "anim_2 - Walking away.inc.c"
#include "anim_3 - Walking away 2.inc.c"
#include "anim_4 - Descend.inc.c"
#include "anim_5 - Descend And Look Down.inc.c"
#include "anim_6 - Look Up And Open Eyes.inc.c"
#include "anim_7 - Mario.inc.c"
#include "anim_8 - Power Of The Stars.inc.c"
#include "anim_9 - Thanks To You.inc.c"
#include "anim_10 - Kiss.inc.c"
#include "anim_11 - Waving.inc.c"
